
import 'dart:convert';

import 'package:flutter/material.dart';
import 'package:shared_preferences/shared_preferences.dart';
import 'package:smartdalala/components/model.dart';
import 'Data.dart';
import 'package:intl/intl.dart';
import 'package:http/http.dart' as http;


bool isInitialized(Autogenerated? obj) {
  // Return true if the object is not null (initialized), otherwise return false
  return obj == null;
}


var itemsList= [
    {
      "ricemill": "kalalla",
      "party": ";als;l,alm",
      "lorry": "ap234assd",
      "Dateobj": "1/10/2024",
      "district": "as k sak kx",
      "paid": false,
      "discount": 1,
      "Bill": [
        {
          "rice": "seeno3",
          "kg": 50,
          "rate": 2340,
          "Bags": 234,
          "received": 0,
          "_id": "66fbfdc5a2d4dcd726c55307"
        }
      ],
      "_id": "66fbfdc5a2d4dcd726c55306"
    },
    {
      "ricemill": "SIRAJ BHANU RM",
      "party": "AURANGABAD FOOD'S",
      "lorry": "MH20GC7568",
      "Dateobj": "22/09/2024",
      "district": "AURANGABAD",
      "paid": false,
      "discount": 4,
      "Bill": [
        {
          "rice": "STM BROKEN",
          "kg": 1,
          "rate": 7000,
          "Bags": 2675,
          "received": 0,
          "_id": "66fbbbdbfe1e6343f5a40034"
        }
      ],
      "_id": "66fbbbdbfe1e6343f5a40033"
    },
    {
      "ricemill": "MAHA LAXMI RM ",
      "party": "AURANGABAD FOOD'S",
      "lorry": "MH20GU8006",
      "Dateobj": "22/09/2024",
      "district": "AURANGABAD",
      "paid": false,
      "discount": 4,
      "Bill": [
        {
          "rice": "LEVI BROKEN",
          "kg": 50,
          "rate": 2700,
          "Bags": 220,
          "received": 0,
          "_id": "66fbb250fe1e6343f5a3ea64"
        }
      ],
      "_id": "66fbb250fe1e6343f5a3ea63"
    },
    {
      "ricemill": "MAHA LAXMI RM ",
      "party": "AURANGABAD FOOD'S",
      "lorry": "MH20GU7863",
      "Dateobj": "22/09/2024",
      "district": "AURANGABAD",
      "paid": false,
      "discount": 4,
      "Bill": [
        {
          "rice": "LEVI BROKEN",
          "kg": 50,
          "rate": 2700,
          "Bags": 240,
          "received": 0,
          "_id": "66fbb227fe1e6343f5a3e950"
        }
      ],
      "_id": "66fbb227fe1e6343f5a3e94f"
    },
    {
      "ricemill": "OM SRI BALAJI",
      "party": "KR ENT",
      "lorry": "TS16UC0271",
      "Dateobj": "23/09/2024",
      "district": "LINGAMPALLY",
      "paid": false,
      "discount": 4,
      "Bill": [
        {
          "rice": "BOILD RNR ",
          "kg": 25,
          "rate": 4000,
          "Bags": 500,
          "received": 0,
          "_id": "66fbb128fe1e6343f5a3e7e4"
        }
      ],
      "_id": "66fbb128fe1e6343f5a3e7e3"
    },
    {
      "ricemill": "TIRUMALA AGRO",
      "party": "VEER ANJANEYA TR'S",
      "lorry": "AP23Y6235",
      "Dateobj": "23/09/2024",
      "district": "KARMANGHAT",
      "paid": false,
      "discount": 4,
      "Bill": [
        {
          "rice": "STM GK RICE",
          "kg": 25,
          "rate": 4800,
          "Bags": 80,
          "received": 0,
          "_id": "66fbb0c9fe1e6343f5a3e6dc"
        }
      ],
      "_id": "66fbb0c9fe1e6343f5a3e6db"
    },
    {
      "ricemill": "TIRUMALA AGRO",
      "party": "LAXMI NARSIMHA TR'S",
      "lorry": "AP23Y6235",
      "Dateobj": "23/09/2024",
      "district": "KARMANGHAT",
      "paid": false,
      "discount": 4,
      "Bill": [
        {
          "rice": "STM GK RICE",
          "kg": 25,
          "rate": 4800,
          "Bags": 260,
          "received": 0,
          "_id": "66fbb096fe1e6343f5a3e5da"
        }
      ],
      "_id": "66fbb096fe1e6343f5a3e5d9"
    },
    {
      "ricemill": "TIRUMALA AGRO",
      "party": "VAISHNAVI ENT",
      "lorry": "AP23Y6235",
      "Dateobj": "23/09/2024",
      "district": "KARMANGHAT",
      "paid": false,
      "discount": 4,
      "Bill": [
        {
          "rice": "STM GK RICE",
          "kg": 25,
          "rate": 4800,
          "Bags": 260,
          "received": 0,
          "_id": "66fbb075fe1e6343f5a3e4de"
        }
      ],
      "_id": "66fbb075fe1e6343f5a3e4dd"
    },
    {
      "ricemill": "TIRUMALA AGRO",
      "party": "TEJA RICE TR'S",
      "lorry": "AP25X3355",
      "Dateobj": "23/09/2024",
      "district": "LINGAMPALLY",
      "paid": false,
      "discount": 4,
      "Bill": [
        {
          "rice": "STM BROKEN",
          "kg": 25,
          "rate": 4800,
          "Bags": 120,
          "_id": "66fbb01cfe1e6343f5a3e3e7"
        },
        {
          "rice": "STM GK RICE",
          "kg": 25,
          "rate": 4800,
          "Bags": 400,
          "received": 0,
          "_id": "66fbb01cfe1e6343f5a3e3e8"
        }
      ],
      "_id": "66fbb01cfe1e6343f5a3e3e6"
    },
    {
      "ricemill": "SATYANARAYAN IND",
      "party": "AURANGABAD FOOD'S",
      "lorry": "MH48CQ2052",
      "Dateobj": "23/09/2024",
      "district": "AURANGABAD",
      "paid": false,
      "discount": 4,
      "Bill": [
        {
          "rice": "LEVI BROKEN",
          "kg": 50,
          "rate": 2711,
          "Bags": 200,
          "received": 0,
          "_id": "66fbaf3efe1e6343f5a3e2fa"
        }
      ],
      "_id": "66fbaf3efe1e6343f5a3e2f9"
    },
    {
      "ricemill": "TIRUMALA AGRO",
      "party": "PARAS SALE'S",
      "lorry": "MH12PQ8146",
      "Dateobj": "23/09/2024",
      "district": "PUNE",
      "paid": false,
      "discount": 4,
      "Bill": [
        {
          "rice": "STM BPT",
          "kg": 26,
          "rate": 3115,
          "Bags": 60,
          "received": 0,
          "_id": "66fbad8bfe1e6343f5a3e213"
        }
      ],
      "_id": "66fbad8bfe1e6343f5a3e212"
    },
    {
      "ricemill": "TIRUMALA AGRO",
      "party": "S.MITTAL RICE WORLD",
      "lorry": "MH12PQ8146",
      "Dateobj": "23/09/2024",
      "district": "PUNE",
      "paid": false,
      "discount": 4,
      "Bill": [
        {
          "rice": "STM BPT",
          "kg": 26,
          "rate": 3115,
          "Bags": 70,
          "received": 0,
          "_id": "66fbad74fe1e6343f5a3e132"
        }
      ],
      "_id": "66fbad74fe1e6343f5a3e131"
    },
    {
      "ricemill": "TIRUMALA AGRO",
      "party": "RAMESH AGENCY",
      "lorry": "MH12PQ8146",
      "Dateobj": "23/09/2024",
      "district": "PUNE",
      "paid": false,
      "discount": 4,
      "Bill": [
        {
          "rice": "STM BPT",
          "kg": 26,
          "rate": 3115,
          "Bags": 80,
          "received": 0,
          "_id": "66fbad55fe1e6343f5a3e057"
        }
      ],
      "_id": "66fbad55fe1e6343f5a3e056"
    },
    {
      "ricemill": "TIRUMALA AGRO",
      "party": " RAJA LAXMI TR'D CO",
      "lorry": "MH12PQ8146",
      "Dateobj": "23/09/2024",
      "district": "PUNE",
      "paid": false,
      "discount": 4,
      "Bill": [
        {
          "rice": "STM BPT",
          "kg": 26,
          "rate": 3115,
          "Bags": 120,
          "received": 0,
          "_id": "66fbad31fe1e6343f5a3df82"
        }
      ],
      "_id": "66fbad31fe1e6343f5a3df81"
    },
    {
      "ricemill": "TIRUMALA AGRO",
      "party": " NEW BALAJI TR'S",
      "lorry": "MH12PQ8146",
      "Dateobj": "23/09/2024",
      "district": "PUNE",
      "paid": false,
      "discount": 4,
      "Bill": [
        {
          "rice": "STM BPT",
          "kg": 26,
          "rate": 3115,
          "Bags": 100,
          "received": 0,
          "_id": "66fbad12fe1e6343f5a3deb3"
        }
      ],
      "_id": "66fbad12fe1e6343f5a3deb2"
    },
    {
      "ricemill": "TIRUMALA AGRO",
      "party": "JOGMAYA SALES",
      "lorry": "MH12PQ8146",
      "Dateobj": "23/09/2024",
      "district": "PUNE",
      "paid": false,
      "discount": 4,
      "Bill": [
        {
          "rice": "STM BPT",
          "kg": 26,
          "rate": 3115,
          "Bags": 100,
          "received": 0,
          "_id": "66fbacf7fe1e6343f5a3ddea"
        }
      ],
      "_id": "66fbacf7fe1e6343f5a3dde9"
    },
    {
      "ricemill": "TIRUMALA AGRO",
      "party": "BANSALI BROTHERS",
      "lorry": "MH12PQ8146",
      "Dateobj": "23/09/2024",
      "district": "PUNE",
      "paid": false,
      "discount": 4,
      "Bill": [
        {
          "rice": "STM BPT",
          "kg": 26,
          "rate": 3115,
          "Bags": 120,
          "received": 0,
          "_id": "66fbacddfe1e6343f5a3dd27"
        }
      ],
      "_id": "66fbacddfe1e6343f5a3dd26"
    },
    {
      "ricemill": "TIRUMALA AGRO",
      "party": "RAJYOG SALES",
      "lorry": "MH12PQ8146",
      "Dateobj": "23/09/2024",
      "district": "PUNE",
      "paid": false,
      "discount": 4,
      "Bill": [
        {
          "rice": "STM BPT",
          "kg": 26,
          "rate": 3115,
          "Bags": 100,
          "received": 0,
          "_id": "66fbacc4fe1e6343f5a3dc6a"
        }
      ],
      "_id": "66fbacc4fe1e6343f5a3dc69"
    },
    {
      "ricemill": "SRI RAMA ANJANEYA AGRO",
      "party": "LAXMI GANPATI",
      "lorry": "TS06UC0523",
      "Dateobj": "24/09/2024",
      "district": "SIDDIPET",
      "paid": false,
      "discount": 4,
      "Bill": [
        {
          "rice": "STM RNR",
          "kg": 26,
          "rate": 5351,
          "Bags": 120,
          "received": 0,
          "_id": "66fba86afe1e6343f5a3d8a3"
        }
      ],
      "_id": "66fba86afe1e6343f5a3d8a2"
    },
    {
      "ricemill": "AYAPPA IND",
      "party": "R NARSIMHULU",
      "lorry": "TS16UC7113",
      "Dateobj": "24/09/2024",
      "district": "GHATKESAR",
      "paid": false,
      "discount": 4,
      "Bill": [
        {
          "rice": "STM GK RICE",
          "kg": 25,
          "rate": 4850,
          "Bags": 16,
          "received": 0,
          "_id": "66fba7b8fe1e6343f5a3d7f1"
        },
        {
          "rice": "BROKEN",
          "kg": 25,
          "rate": 2900,
          "Bags": 64,
          "_id": "66fba7b8fe1e6343f5a3d7f2"
        }
      ],
      "_id": "66fba7b8fe1e6343f5a3d7f0"
    },
    {
      "ricemill": "RUDRA IND",
      "party": "R NARSIMHULU",
      "lorry": "TS16UC7113",
      "Dateobj": "24/09/2024",
      "district": "GHATKESAR",
      "paid": false,
      "discount": 4,
      "Bill": [
        {
          "rice": "STM GK",
          "kg": 25,
          "rate": 4825,
          "Bags": 400,
          "received": 0,
          "_id": "66fba76afe1e6343f5a3d749"
        }
      ],
      "_id": "66fba76afe1e6343f5a3d748"
    },
    {
      "ricemill": "Satyanarayan Ind",
      "party": "OM TRD CO",
      "lorry": "MH20GC8027",
      "Dateobj": "24/09/2024",
      "district": "Aurangabad",
      "paid": false,
      "discount": 4,
      "Bill": [
        {
          "rice": "LEVI BROKEN ",
          "kg": 26,
          "rate": 3895,
          "Bags": 231,
          "received": 0,
          "_id": "66fba6e0fe1e6343f5a3d6a7"
        }
      ],
      "_id": "66fba6e0fe1e6343f5a3d6a6"
    },
    {
      "ricemill": "Satyanarayan Ind",
      "party": "Aurangabad Food's",
      "lorry": "MH20GC8027",
      "Dateobj": "24/09/2024",
      "district": "Aurangabad",
      "paid": false,
      "discount": 4,
      "Bill": [
        {
          "rice": "LEVI BROKEN ",
          "kg": 2711,
          "rate": 2.8,
          "Bags": 25,
          "received": 0,
          "_id": "66fbb617fe1e6343f5a3f338"
        }
      ],
      "_id": "66fbb617fe1e6343f5a3f337"
    },
    {
      "ricemill": "MVR IND",
      "party": "SHUBAM TRADING CO",
      "lorry": "MP20HB7551",
      "Dateobj": "25/09/2024",
      "district": "Barghat",
      "paid": false,
      "discount": 4,
      "Bill": [
        {
          "rice": "RAW JSR",
          "kg": 0,
          "rate": 0,
          "Bags": 0,
          "received": 0,
          "_id": "66fba3fafe1e6343f5a3d49d"
        }
      ],
      "_id": "66fba3fafe1e6343f5a3d49c"
    },
    {
      "ricemill": "AYAPPA IND",
      "party": "SHUBAM TRADING CO",
      "lorry": "MP20HB7551",
      "Dateobj": "25/09/2024",
      "district": "Barghat",
      "paid": false,
      "discount": 4,
      "Bill": [
        {
          "rice": "RAW JSR",
          "kg": 26,
          "rate": 3650,
          "Bags": 75,
          "received": 0,
          "_id": "66fba3b7fe1e6343f5a3d40d"
        }
      ],
      "_id": "66fba3b7fe1e6343f5a3d40c"
    },
    {
      "ricemill": "RK RICE MILL",
      "party": "SHUBAM TRADING CO",
      "lorry": "MP20HB7551",
      "Dateobj": "25/09/2024",
      "district": "Barghat",
      "paid": false,
      "discount": 4,
      "Bill": [
        {
          "rice": "HMT BROKEN ",
          "kg": 26,
          "rate": 2875,
          "Bags": 420,
          "received": 0,
          "_id": "66fba389fe1e6343f5a3d383"
        }
      ],
      "_id": "66fba389fe1e6343f5a3d382"
    },
    {
      "ricemill": "SRI RAMA RICE MILL",
      "party": "SHUBAM TRADING CO",
      "lorry": "MP20HB7551",
      "Dateobj": "25/09/2024",
      "district": "Barghat",
      "paid": false,
      "discount": 4,
      "Bill": [
        {
          "rice": "STM JSR ",
          "kg": 210,
          "rate": 26,
          "Bags": 3100,
          "received": 0,
          "_id": "66fba9f7fe1e6343f5a3db62"
        },
        {
          "rice": "RAW JSR",
          "kg": 156,
          "rate": 26,
          "Bags": 2925,
          "received": 0,
          "_id": "66fba9f7fe1e6343f5a3db63"
        }
      ],
      "_id": "66fba9f7fe1e6343f5a3db61"
    },
    {
      "ricemill": "SRI RAM AJANEYA",
      "party": "Shiv Kirana",
      "lorry": "MP22H0793",
      "Dateobj": "26/09/2024",
      "district": "Barghat",
      "paid": false,
      "discount": 4,
      "Bill": [
        {
          "rice": "RNR BORKEN",
          "kg": 26,
          "rate": 2850,
          "Bags": 5,
          "_id": "66fba242fe1e6343f5a3d281"
        },
        {
          "rice": "RNR BROKEN",
          "kg": 26,
          "rate": 3000,
          "Bags": 352,
          "_id": "66fba242fe1e6343f5a3d282"
        },
        {
          "rice": "RAW JSR",
          "kg": 26,
          "rate": 3660,
          "Bags": 76,
          "received": 0,
          "_id": "66fba242fe1e6343f5a3d283"
        }
      ],
      "_id": "66fba242fe1e6343f5a3d280"
    },
    {
      "ricemill": "Rudra Ind",
      "party": "Shiv Kirana",
      "lorry": "MP22H0793",
      "Dateobj": "26/09/2024",
      "district": "Barghat",
      "paid": false,
      "discount": 4,
      "Bill": [
        {
          "rice": "RAW JSR",
          "kg": 26,
          "rate": 3675,
          "Bags": 230,
          "received": 0,
          "_id": "66fba1c1fe1e6343f5a3d212"
        }
      ],
      "_id": "66fba1c1fe1e6343f5a3d211"
    },
    {
      "ricemill": "RK Rice Mill",
      "party": "Shiv Kirana",
      "lorry": "MP22H0793",
      "Dateobj": "26/09/2024",
      "district": "Barghat",
      "paid": false,
      "discount": 4,
      "Bill": [
        {
          "rice": "RAW JSR",
          "kg": 26,
          "rate": 3875,
          "Bags": 80,
          "received": 0,
          "_id": "66fba18efe1e6343f5a3d1a8"
        },
        {
          "rice": "DAGI HMT",
          "kg": 26,
          "rate": 2875,
          "Bags": 219,
          "_id": "66fba18efe1e6343f5a3d1a9"
        }
      ],
      "_id": "66fba18efe1e6343f5a3d1a7"
    },
    {
      "ricemill": "Ayappa Ind",
      "party": "Raj Dhani Grain house",
      "lorry": "MH12CH5126",
      "Dateobj": "28/09/2024",
      "district": "Pune",
      "paid": false,
      "discount": 4,
      "Bill": [
        {
          "rice": "BROKEN",
          "kg": 26,
          "rate": 2940,
          "Bags": 142,
          "received": 0,
          "_id": "66fba094fe1e6343f5a3d148"
        }
      ],
      "_id": "66fba094fe1e6343f5a3d147"
    },
    {
      "ricemill": "Ayappa Ind",
      "party": "JAY Kumar & Brother's",
      "lorry": "MH12CH5126",
      "Dateobj": "28/09/2024",
      "district": "Pune",
      "paid": false,
      "discount": 4,
      "Bill": [
        {
          "rice": "BROKEN",
          "kg": 26,
          "rate": 2940,
          "Bags": 80,
          "received": 0,
          "_id": "66fba074fe1e6343f5a3d0ee"
        }
      ],
      "_id": "66fba074fe1e6343f5a3d0ed"
    },
    {
      "ricemill": "Ayappa Ind",
      "party": "Bansilal Nemichand Oswal",
      "lorry": "MH12CH5126",
      "Dateobj": "28/09/2024",
      "district": "Pune",
      "paid": false,
      "discount": 4,
      "Bill": [
        {
          "rice": "BROKEN",
          "kg": 26,
          "rate": 2940,
          "Bags": 80,
          "received": 0,
          "_id": "66fba05dfe1e6343f5a3d09a"
        }
      ],
      "_id": "66fba05dfe1e6343f5a3d099"
    },
    {
      "ricemill": "Ayappa Ind",
      "party": "Shreya's Co",
      "lorry": "MH12CH5126",
      "Dateobj": "28/09/2024",
      "district": "Pune",
      "paid": false,
      "discount": 4,
      "Bill": [
        {
          "rice": "BROKEN",
          "kg": 26,
          "rate": 2940,
          "Bags": 80,
          "received": 0,
          "_id": "66fba026fe1e6343f5a3d04c"
        }
      ],
      "_id": "66fba026fe1e6343f5a3d04b"
    },
    {
      "ricemill": "Ayappa Ind",
      "party": "k. kathari Co",
      "lorry": "MH12CH5126",
      "Dateobj": "28/09/2024",
      "district": "Pune",
      "paid": false,
      "discount": 4,
      "Bill": [
        {
          "rice": "BROKEN",
          "kg": 26,
          "rate": 2940,
          "Bags": 80,
          "received": 0,
          "_id": "66fba006fe1e6343f5a3d004"
        }
      ],
      "_id": "66fba006fe1e6343f5a3d003"
    },
    {
      "ricemill": "Tirumala Agro",
      "party": "Vijay Traders",
      "lorry": "MH50N0997",
      "Dateobj": "25/09/2024",
      "district": "Moshi , Pune",
      "paid": false,
      "discount": 4,
      "Bill": [
        {
          "rice": "BOKEN",
          "kg": 26,
          "rate": 3121,
          "Bags": 462,
          "received": 0,
          "_id": "66fb9c34fe1e6343f5a3cfc2"
        }
      ],
      "_id": "66fb9c34fe1e6343f5a3cfc1"
    },
    {
      "ricemill": "OM SRI Balaji ",
      "party": "KR ENT",
      "lorry": "TS16UC0271",
      "Dateobj": "25/09/2024",
      "district": "LINGAMPALLY",
      "paid": false,
      "discount": 4,
      "Bill": [
        {
          "rice": "BOILD RNR",
          "kg": 25,
          "rate": 3991,
          "Bags": 520,
          "received": 0,
          "_id": "66fb9b52fe1e6343f5a3cf86"
        }
      ],
      "_id": "66fb9b52fe1e6343f5a3cf85"
    },
    {
      "ricemill": "OM Balaji ",
      "party": "Balaji Govidh Ent",
      "lorry": "TS16UC7113",
      "Dateobj": "26/09/2024",
      "district": "Narsingi",
      "paid": false,
      "discount": 4,
      "Bill": [
        {
          "rice": "BOILD RNR",
          "kg": 25,
          "rate": 4141,
          "Bags": 600,
          "received": 0,
          "_id": "66fb9a61fe1e6343f5a3cf50"
        }
      ],
      "_id": "66fb9a61fe1e6343f5a3cf4f"
    },
    {
      "ricemill": "Rudra Ind",
      "party": "Raja Rajeshwara Tr's",
      "lorry": "AP25X3355",
      "Dateobj": "26/09/2024",
      "district": "Karmanghat",
      "paid": false,
      "discount": 4,
      "Bill": [
        {
          "rice": "STM BPT RICE",
          "kg": 200,
          "rate": 25,
          "Bags": 4850,
          "received": 0,
          "_id": "66fb9997fe1e6343f5a3cecf"
        }
      ],
      "_id": "66fb9997fe1e6343f5a3cece"
    },
    {
      "ricemill": "Rudra Ind",
      "party": "Krishna Tr's",
      "lorry": "AP25X3355",
      "Dateobj": "26/09/2024",
      "district": "Karmanghat",
      "paid": false,
      "discount": 4,
      "Bill": [
        {
          "rice": "STM BPT RICE",
          "kg": 140,
          "rate": 25,
          "Bags": 4850,
          "received": 0,
          "_id": "66fb99a7fe1e6343f5a3cefa"
        }
      ],
      "_id": "66fb99a7fe1e6343f5a3cef9"
    },
    {
      "ricemill": "Rudra Ind",
      "party": "Veera Venkateshwara Tr's",
      "lorry": "AP25X3355",
      "Dateobj": "26/09/2024",
      "district": "Karmanghat",
      "paid": false,
      "discount": 4,
      "Bill": [
        {
          "rice": "STM BPT RICE",
          "kg": 160,
          "rate": 25,
          "Bags": 4850,
          "received": 0,
          "_id": "66fb99b1fe1e6343f5a3cf25"
        }
      ],
      "_id": "66fb99b1fe1e6343f5a3cf24"
    }
  ];


String path="https://corporations-1.onrender.com";
// String path="http://localhost:3000";
// String userid="64fda9371c399ddb635b44d3";
String userid="65082be045f077be1f9c1716";
// String userid="64db2fd4c5a6f316ac4549a6";

class Add extends StatefulWidget {
  const Add({ Key? key }) : super(key: key);

  @override
  _AddState createState() => _AddState();
}

class _AddState extends State<Add> {
  //  final dateob = new DateTime.now();
  //  var formatter = DateFormat('yMd').format(DateTime.now());
    bool clicked=false;
    TextEditingController DateObj=new TextEditingController(text:DateFormat('d/MM/yyyy').format(DateTime.now()).toString() );
    final RiceMillName=new TextEditingController();
    final PartyName=new TextEditingController();
    final District=new TextEditingController();
    final Sno=new TextEditingController(text: '1');
    final phoneno=new TextEditingController();
    final TransPort=new TextEditingController();
    final LorryNo=new TextEditingController();
    final Kiraya=new TextEditingController();
    final Advance=new TextEditingController();
    final Discount=new TextEditingController();

    final RiceName=new TextEditingController();
    final Kgs=new TextEditingController();
    final Bags=new TextEditingController();
    final Rate=new TextEditingController();

    final RiceName2=new TextEditingController();
    final Kgs2=new TextEditingController();
    final Bags2=new TextEditingController();
    final Rate2=new TextEditingController();

    final RiceName3=new TextEditingController();
    final Kgs3=new TextEditingController();
    final Bags3=new TextEditingController();
    final Rate3=new TextEditingController();

   var list=[1,3];
   int no=1;
   bool bill1=true;
   bool bill2=true;
   bool bill3=true;
   bool paid=false;

   var Bill=[];

   void storeData()async{
      
          final SharedPreferences Detailsuser = await SharedPreferences.getInstance();
          final String id = Detailsuser.getString('id').toString();
     final response = await http.post(
    Uri.parse('${path}/additem/'+userid),
    headers: <String, String>{
      'Content-Type': 'application/json; charset=UTF-8',
    },
    body: jsonEncode({
           'ricemill':RiceMillName.text,
        'party':PartyName.text,
        'lorry':LorryNo.text,
        'Dateobj':DateObj.text,
        'district':District.text,
        'phoneNo':phoneno.text,
        'Transport':TransPort.text,
        'kiraya':Kiraya.text,
        'advance':Advance.text,
        'discount':Discount.text,
        'paid':paid,
        'Bill':Bill
       }),
    
     
  );

    setState(() {
                                                    Bill.clear();
                                                    bill1=true;
                                                    bill2=true;
                                                    bill3=true;
         });


     print({
           'ricemill':RiceMillName.text,
        'party':PartyName.text,
        'lorry':LorryNo.text,
        'Dateobj':DateObj.text,
        'district':District.text,
        'phoneNo':phoneno.text,
        'Transport':TransPort.text,
        'kiraya':Kiraya.text,
        'advance':Advance.text,
        'discount':Discount.text,
        'paid':paid,
        'Bill':Bill
       });

       print("added data");



   }
   void storeDataList()async
   {
      
          final SharedPreferences Detailsuser = await SharedPreferences.getInstance();
          final String id = Detailsuser.getString('id').toString();

          for(int i=0;i<itemsList.length;i++)
          {
                  final response = await http.post(
                  Uri.parse('${path}/additem/'+userid),
                  headers: <String, String>{
                    'Content-Type': 'application/json; charset=UTF-8',
                  },
                  body: jsonEncode(itemsList[i]),);
                  print(response.statusCode);
          }
   }


   Widget Input(lableText,keyBoard,Textcontroller,icons){
      // print(Textcontroller);
      return Center(
        child: Container(
          padding: EdgeInsets.symmetric(vertical: 10),
          width: MediaQuery.of(context).size.width/1.1,
          child: TextFormField(
               keyboardType: keyBoard,
                controller: Textcontroller,
              decoration: InputDecoration(
                labelText: lableText,
                border: OutlineInputBorder(),
                suffixIcon: Icon(icons),
              ),
            ),
        ),
      );
   }

  Widget InputDate(lableText,keyBoard,Textcontroller,icons){

    return Center(
        child: Container(
          padding: EdgeInsets.symmetric(vertical: 10),
          width: MediaQuery.of(context).size.width/1.1,
          child: TextFormField(
               keyboardType: keyBoard,
                controller: DateObj,
              decoration: InputDecoration(
                labelText: lableText,
                hintText: Sno.text,
                border: OutlineInputBorder(),
                suffixIcon:IconButton( onPressed: ()async{
                      DateTime? dateTime=await showDatePicker(context: context, initialDate: DateTime.now(),
                       firstDate: DateTime(2021), lastDate: DateTime(2025));
                       setState(() {
                           if(dateTime!=null){
                               String str=new DateFormat("dd/MM/yyyy").format(dateTime);
                               DateObj.text=str;
                           }

                       });
                },icon:Icon( Icons.date_range_outlined)),
              ),
            ),
        ),
      );


  }


   Widget InputSno(){
      // print(Textcontroller);
      return Row(
        children: [
              SizedBox(width: 20,),
              CircleAvatar(
                child: IconButton(icon:Icon(Icons.remove,color:Colors.purple,),onPressed: (){
                                setState(() {
                                   if(no>0)no--;
                                    StringData.sno=no.toString();
                                    Sno.text=no.toString();
                                });
                      },),
              ),
              SizedBox(width: 10,),
          Container(
            padding: EdgeInsets.symmetric(vertical: 10),
            width: MediaQuery.of(context).size.width/2,
            child: TextFormField(
                 keyboardType: TextInputType.number,
                  controller: Sno,
                  onChanged: (value) {
                       setState(() {
                         no= int.parse(Sno.text);
                       });
                  },
                decoration: InputDecoration(
                  labelText: "S.no",

                  border: OutlineInputBorder(),
            
                ),
              ),
          ),
          SizedBox(width: 10,),
           CircleAvatar(
            // color: Colors.black,
             child: IconButton(icon:Icon(Icons.add,color:Colors.purple,),onPressed: (){
                         setState(() {
                              no++;
                             StringData.sno=no.toString();
                              Sno.text=no.toString();
                         });
               },),
           ),
          
        ],
      );
   }


  


   Widget AddItems(index){
      return ListView(children: [
          //  Input("RiceName",TextInputType.name),
          //  Input("Rate",TextInputType.number),
          //  Input("Bags",TextInputType.number),
          //  Input("Kgs",TextInputType.number), 
      ]);
   }

   void ResetData(){
               
            setState(() {
                DateObj.text=DateFormat('yMd').format(DateTime.now()).toString();
                RiceMillName.text="";
                PartyName.text="";
                District.text="";
                TransPort.text="";
                LorryNo.text="";
                Kiraya.text="";
                Advance.text="";
                Discount.text="";
                RiceName.text="";
                Kgs.text="";
                Bags.text="";
                Rate.text="";

            });
   }


  @override
  Widget build(BuildContext context) {
  //  print(formatter);
  
    return  Scaffold(
      drawer: Drawer(),
      appBar: AppBar(
               backgroundColor: Colors.orange,
               title: Center(child: Text("Letter Pad",style: TextStyle(
                     color: Colors.black,
                     fontSize: 25,
                     fontWeight: FontWeight.bold
               ),)),
          ),
      body: SingleChildScrollView(
        child:  Container(
               child:  Column(   
                     mainAxisAlignment: MainAxisAlignment.center,
                     crossAxisAlignment: CrossAxisAlignment.center,
                     children: [

                      
                        InputDate("Date",TextInputType.datetime,DateObj,Icons.data_exploration),
                        Input("RiceMillName",TextInputType.name,RiceMillName,Icons.near_me),
                        Input("PartyName",TextInputType.name,PartyName,Icons.near_me),
                        Input("District",TextInputType.name,District,Icons.place),
                        Input("TransPort",TextInputType.name,TransPort,Icons.transform_sharp),
                        Input("Lorry No",TextInputType.name,LorryNo,Icons.nat),
                        Input("Discount",TextInputType.number,Discount,Icons.discord),

                        
                        Container(
                          height: 500,
                          child: ListView(
                            scrollDirection: Axis.horizontal,
                            children: [
                              Card(
                                elevation: 3,
                                child: Container(
                                    width: MediaQuery.of(context).size.width/1.1,
                                    padding: EdgeInsets.symmetric(vertical: 20,horizontal: 25),
                                    decoration: BoxDecoration(
                                      // color: const Color.fromARGB(255, 236, 234, 234),
                                        // border: Border.all(
                                        //       // color: Colors.orange
                                        // )
                                    ),
                                    child: Column(
                                         children: [
                                                Align(alignment:Alignment.topRight ,child:Text("1/3")),
                                              Input("Rice Name",TextInputType.name,RiceName,Icons.near_me),
                                              Input("Bags",TextInputType.number,Bags,Icons.badge_sharp),
                                              Input("Kgs",TextInputType.number,Kgs,Icons.king_bed_sharp),
                                              Input("Rate",TextInputType.number,Rate,Icons.radio),
                                              Padding(
                          padding: const EdgeInsets.symmetric(vertical:12.0),
                          child: Card(
                            child: Container(
                              width: MediaQuery.of(context).size.width/1.1,
                              color: bill1?Colors.green:Colors.black,
                              child: InkWell(
                                  onTap:(){
                                     setState(() {
                                       bill1=false;
                                      Bill.add(
                                         {
                                            'rice':RiceName.text,
                                            'kg':Kgs.text,
                                            'rate':Rate.text,
                                            'Bags':Bags.text,
                                            'received':0,
                                        }
                                     );
                                    });
                                      
                                  },
                                  child:const Text("ADD Data",
                                  style: TextStyle(
                                                      fontSize: 30,
                                                      
                                                      color: Colors.white
                                                  ),
                                                    textAlign: TextAlign.center,),
                              ),
                            ),
                          ),
                        ),  
                                         ],
                                    ),
                                ),
                              ),
                              Card(
                                elevation: 3,
                                child: Container(
                                    width: MediaQuery.of(context).size.width/1.1,
                                    padding: EdgeInsets.symmetric(vertical: 20,horizontal: 25),
                                    decoration: BoxDecoration(
                                      // color: const Color.fromARGB(255, 236, 234, 234),
                                        // border: Border.all(
                                        //       // color: Colors.orange
                                        // )
                                    ),
                                    child: Column(
                                         children: [
                                                Align(alignment:Alignment.topRight ,child:Text("2/3")),
                                              Input("Rice Name",TextInputType.name,RiceName2,Icons.near_me),
                                              Input("Bags",TextInputType.number,Bags2,Icons.badge_sharp),
                                              Input("Kgs",TextInputType.number,Kgs2,Icons.king_bed_sharp),
                                              Input("Rate",TextInputType.number,Rate2,Icons.radio),
                                              Padding(
                          padding: const EdgeInsets.symmetric(vertical:12.0),
                          child: Card(
                            child: Container(
                              width: MediaQuery.of(context).size.width/1.1,
                              color:   bill2?Colors.green:Colors.black,
                              child: InkWell(
                                  onTap:(){
                                     setState(() {
                                       bill2=false;
                                    Bill.add(
                                         {
                                            'rice':RiceName2.text,
                                            'kg':Kgs2.text,
                                            'rate':Rate2.text,
                                            'Bags':Bags2.text,
                                        }
                                    );
                                     });
                                        
                                  },
                                  child:const Text("ADD Data",
                                  style: TextStyle(
                                                      fontSize: 30,
                                                      
                                                      color: Colors.white
                                                  ),
                                                    textAlign: TextAlign.center,),
                              ),
                            ),
                          ),
                        ),  
                                         ],
                                    ),
                                ),
                              ),
                              Card(
                                elevation: 3,
                                child: Container(
                                    width: MediaQuery.of(context).size.width/1.1,
                                    padding: EdgeInsets.symmetric(vertical: 20,horizontal: 25),
                                    decoration: BoxDecoration(
                                      // color: const Color.fromARGB(255, 236, 234, 234),
                                        // border: Border.all(
                                        //       // color: Colors.orange
                                        // )
                                    ),
                                    child: Column(
                                         children: [
                                                Align(alignment:Alignment.topRight ,child:Text("3/3")),
                                              Input("Rice Name",TextInputType.name,RiceName3,Icons.near_me),
                                              Input("Bags",TextInputType.number,Bags3,Icons.badge_sharp),
                                              Input("Kgs",TextInputType.number,Kgs3,Icons.king_bed_sharp),
                                              Input("Rate",TextInputType.number,Rate3,Icons.radio),
                                               Padding(
                          padding: const EdgeInsets.symmetric(vertical:12.0),
                          child: Card(
                            child: Container(
                              width: MediaQuery.of(context).size.width/1.1,
                              color: bill3?Colors.green:Colors.black,
                              child: InkWell(
                                  onTap:(){
                                    setState(() {
                                        bill3=false;

                                        Bill.add(
                                         {
                                            'rice':RiceName3.text,
                                            'kg':Kgs3.text,
                                            'rate':Rate3.text,
                                            'Bags':Bags3.text,
                                        }
                                    );
                                    });

                                  
                                      
                                  },
                                  child:const Text("ADD Data",
                                  style: TextStyle(
                                                      fontSize: 30,
                                                      
                                                      color: Colors.white
                                                  ),
                                                    textAlign: TextAlign.center,),
                              ),
                            ),
                          ),
                        ), 
                                         ],
                                    ),
                                ),
                              ),
                            ],
                          ),
                        ),

                      //  Padding(
                      //     padding: const EdgeInsets.symmetric(vertical:12.0),
                      //     child: Card(
                      //       child: Container(
                      //         width: MediaQuery.of(context).size.width/1.1,
                      //         color: clicked? Colors.brown:Colors.pink,
                      //         child: InkWell(
                      //             onTap:!clicked? (){
                                    
                      //                 setState(() {
                      //                     clicked=true;
                      //                 });
                      //                 storeData();
                      //             }:null,
                      //             child:const Text("ADD To DB",
                      //             style: TextStyle(
                      //                                 fontSize: 30,
                                                      
                      //                                 color: Colors.white
                      //                             ),
                      //                               textAlign: TextAlign.center,),
                      //         ),
                      //       ),
                      //     ),
                      //   ),  
    
                        // Padding(
                        //   padding: const EdgeInsets.all(8.0),
                        //   child: Row(
                        //       mainAxisAlignment: MainAxisAlignment.spaceAround,
                        //       children: [
                                   
                        //             Expanded(
                        //               flex: 1,
                        //               child: Card(
                        //                 elevation: 2,
                        //                 child: Container(
                        //                   padding: EdgeInsets.symmetric(horizontal: 20,vertical: 5),
                        //                    decoration: BoxDecoration(
                        //                     color: Colors.green,
                        //                     borderRadius: BorderRadius.circular(12),
                        //                     border: Border.all(color: Colors.black,width: 3)
                        //                   ),
                        //                   child: InkWell(
                        //                     onTap: () {
                        //                      
                        //                        setState(() {
                                                
                        //                          StringData.DateObj=DateObj.text;
                        //                          StringData.RiceMillName=RiceMillName.text;
                        //                          StringData.PartyName=PartyName.text;
                        //                          StringData.District=District.text;
                        //                          StringData.phoneno=phoneno.text;
                        //                          StringData.TransPort=TransPort.text;
                        //                          StringData.LorryNo=LorryNo.text;
                        //                          StringData.Kiraya=Kiraya.text;
                        //                          if(Advance.text==""){
                        //                               StringData.Advance="0";
                        //                          }else{
                        //                             StringData.Advance=Advance.text;

                        //                          }
                        //                        if(Discount.text==""){
                        //                            StringData.Discount="-";
                        //                        }else{
                        //                           StringData.Discount=Discount.text;
                        //                        }
                        //                          StringData.RiceName=RiceName.text;
                        //                          StringData.Bags=Bags.text;
                        //                          StringData.Kgs=Kgs.text;
                        //                          StringData.Rate=Rate.text;
                        //                          StringData.sno=Sno.text;
                                                

                        //                        });
                        //                          Navigator.pushNamed(context, '/print',);  
                        //                     },
                        //                     child: Text("Print",style: TextStyle(
                        //                         fontSize: 30,
                        //                         color: Colors.white
                        //                     ),
                        //                     textAlign: TextAlign.center,
                        //                     ),
                        //                    ),
                        //                 ),
                        //               ),
                        //             ),
    
                                  
                        //             Expanded(
                        //               flex: 1,
                        //               child: Card(
                        //                 elevation: 2,
                        //                 child: Container(
                                          
                        //                   padding: EdgeInsets.symmetric(horizontal: 20,vertical: 5),
                        //                    decoration: BoxDecoration(
                        //                     color: Colors.red,
                        //                      borderRadius: BorderRadius.circular(12),
                        //                     border: Border.all(color: Colors.black,width: 3)
                        //                   ),
                        //                   child: InkWell(
                        //                     onTap: () {
                        //                       ResetData();
                        //                     },
                        //                     child: Text("Reset",style: TextStyle(
                        //                         fontSize: 30,
                                                
                        //                         color: Colors.white
                        //                     ),
                        //                       textAlign: TextAlign.center,
                        //                     ),
                        //                    ),
                        //                 ),
                        //               ),
                        //             ),
                                     
                                    
                                  
                        //       ],
                        //   ),
                        // ),
                        

                      Padding(
                        padding: const EdgeInsets.only(top: 39.0),
                        child: Card(
                          elevation: 3,
                          child: Container(
                            // color: Colors.deepOrange,
                            padding: const EdgeInsets.only(top: 10,bottom: 10),
                            child: Row(
                                mainAxisAlignment: MainAxisAlignment.spaceAround,
                                children: [
                                       Column(
                                        children: [
                                           InkWell(
                                              onTap: (){
                                              
                                                storeData();
                                                // storeDataList();
                                                // setState(() {
                                                //     Bill.clear();
                                                // });
                                                  
                                            },
                                            child: Icon(Icons.dashboard_customize)
                                          ),
                                          SizedBox(height: 10,),
                                          Text("DataBase")
                                        ],
                                       ),
                                        Column(
                                        children: [
                                           InkWell(
                                                              onTap: () {
                                             
                                               setState(() {
                                                
                                                 StringData.DateObj=DateObj.text;
                                                 StringData.RiceMillName=RiceMillName.text;
                                                 StringData.PartyName=PartyName.text;
                                                 StringData.District=District.text;
                                                 StringData.phoneno=phoneno.text;
                                                 StringData.TransPort=TransPort.text;
                                                 StringData.LorryNo=LorryNo.text;
                                                 StringData.Kiraya=Kiraya.text;
                                                 if(Advance.text==""){
                                                      StringData.Advance="0";
                                                 }else{
                                                    StringData.Advance=Advance.text;

                                                 }
                                               if(Discount.text==""){
                                                   StringData.Discount="-";
                                               }else{
                                                  StringData.Discount=Discount.text;
                                               }
                                                 StringData.RiceName=RiceName.text;
                                                 StringData.Bags=Bags.text;
                                                 StringData.Kgs=Kgs.text;
                                                 StringData.Rate=Rate.text;
                                                 StringData.sno=Sno.text;
                                                

                                               });
                                                 Navigator.pushNamed(context, '/print',);  
                                            },
                                            child: Icon(Icons.print)
                                          ),
                                          SizedBox(height: 10,),
                                          Text("Print")
                                        ],
                                       ),
                                        Column(
                                        children: [
                                           InkWell(
                                            onTap: () {
                                                  ResetData();
                                            },
                                            child: Icon(Icons.reset_tv)
                                          ),
                                          SizedBox(height: 10,),
                                          Text("reset")
                                        ],
                                       ),
                                      
                                        Column(
                                        children: [
                                           InkWell(
                                            onTap: () {
                                                  Navigator.pushNamed(context, '/Menu',);  
                                            },
                                            child: Icon(Icons.reset_tv)
                                          ),
                                          SizedBox(height: 10,),
                                          Text("Home")
                                        ],
                                       )
                                ],
                            ),
                          ),
                        ),
                      )
                       
                      
                     ],
               ),
        ),
      ),
    );
  }
}