import 'dart:convert';

import 'package:flutter/material.dart';
import 'package:flutter/services.dart';
import 'package:http/http.dart' as http;
import 'package:shared_preferences/shared_preferences.dart';
import 'package:smartdalala/components/add.dart';

import 'model.dart';


class Dalailist extends StatefulWidget {
  const Dalailist({ Key? key }) : super(key: key);

  @override
  _DalailistState createState() => _DalailistState();
}

class _DalailistState extends State<Dalailist> {
  late Autogenerated data;
 bool flag=true;


  void getdata()async{
          final SharedPreferences Detailsuser = await SharedPreferences.getInstance();
          final String id = Detailsuser.getString('id').toString();
          // var url=path+'/'+userid+"/"+itId;
          var url=path+'/admin/payment/'+userid;
          final response = await http.get(Uri.parse(url));
          if (response.statusCode == 200) {
              print(response.body);
               setState(() {
               data = Autogenerated.fromJson(jsonDecode(response.body));
               flag=false;
              });
             
          } else {
            throw Exception('Failed to load album');
          }
  }

 @override
  void initState() {
    getdata();
    super.initState();
  }


  void deletedala(itId)async{
      // /admin/payment/:userid/:itemid
       final SharedPreferences Detailsuser = await SharedPreferences.getInstance();
          final String id = Detailsuser.getString('id').toString();
    var url=path+"/admin/payment/"+userid+"/"+itId;

     final http.Response response = await http.delete(Uri.parse(url),
          headers: <String, String>{
            'Content-Type': 'application/json; charset=UTF-8',
          },
      );
      setState(() {
        
      });
      Navigator.pushReplacement(
        context,
        MaterialPageRoute(
            builder: (BuildContext context) => super.widget));

  } 
  
  @override
  Widget build(BuildContext context) {
   
    if(flag)return  Scaffold(
        drawer: Drawer(),
      appBar: AppBar(
               backgroundColor: Colors.orange,
               title:const Center(child: Text("Smart Dalal",style: TextStyle(
                     color: Colors.black,
                     fontSize: 25,
                     fontWeight: FontWeight.bold
               ),)),
          ),body: Center(child: CircularProgressIndicator(color: Colors.red,strokeWidth: 20),));

    List<Payment>? list=data!=null?data.payment:null;

    return Scaffold(
        drawer: Drawer(),
      appBar: AppBar(
               backgroundColor: Colors.orange,
               title:const Center(child: Text("Smart Dalal",style: TextStyle(
                     color: Colors.black,
                     fontSize: 25,
                     fontWeight: FontWeight.bold
               ),)),
          ),
      body:flag?  Text("Loading...."):Container(
        height: MediaQuery.of(context).size.height/1.1,
        width: MediaQuery.of(context).size.width,
        child: SingleChildScrollView(
          child: Column(
            mainAxisAlignment: MainAxisAlignment.center,
            crossAxisAlignment: CrossAxisAlignment.center,
            children: list?.map((payment) {
              return Dal(payment);
            }).toList() ?? [], 
          ),
        ),
      ),
    );
  }


  Widget Dal(Payment obj){
  

    return Card(
      child: Container(
                padding: const EdgeInsets.symmetric(horizontal: 10,vertical: 10),
                width: MediaQuery.of(context).size.width/1.1,
                child: Column(
                    crossAxisAlignment: CrossAxisAlignment.center,
                     children: [
                          // const  SizedBox(height: 5,),
                            Padding(
                              padding: const EdgeInsets.only(left:8.0),
                              child: Text(obj.dateobj.toString(),style: TextStyle(
                                  color: Colors.red,
                                  fontSize: 15,
                                  fontWeight: FontWeight.bold
                            ),)),
                            
                                
                            ListTile(
                              title: Row(
                                mainAxisAlignment: MainAxisAlignment.spaceBetween,
                                children: [
                                  Text(
                                    obj.name.toString().toUpperCase(),
                                    textScaleFactor: 1.1,
                                  ),
                                   Text("₹"+obj.amount.toString(),style: TextStyle(
                                                color: Colors.black,
                                                fontSize: 15,
                                                fontWeight: FontWeight.bold
                                          ),),
                                ],
                              ),
                              trailing: InkWell(
                                   onTap: (){
                                        deletedala(obj.sId);
                                   },
                                   child: Icon(Icons.delete,color: Colors.red,)
                                ),
                            ),
                                
                            Padding(
                              padding: const EdgeInsets.only(left:18.0,top: 10),
                              child: Row(
                                  mainAxisAlignment: MainAxisAlignment.spaceAround,
                                  children: [
                                      //  Text("₹"+obj.amount.toString(),style: TextStyle(
                                      //           color: Colors.black,
                                      //           fontSize: 15,
                                      //           fontWeight: FontWeight.bold
                                      //     ),),
                                
                                        //  Row(
                                        //     children: [
                                        //         Icon(Icons.person,color: Colors.red,),
                                        //          Text(obj.transport.toString(),style: TextStyle(
                                        //         color: Colors.black,
                                        //         fontSize: 15,
                                        //         fontWeight: FontWeight.bold
                                        //   ),),
                                        //     ],
                                        //  ),
                                
                                        //  Row(
                                        //     mainAxisAlignment: MainAxisAlignment.spaceBetween,
                                        //     children: [
                                        //         Icon(Icons.phone,color: Colors.pinkAccent,),
                                        //          Text(obj.contactno.toString(),style: TextStyle(
                                        //         color: Colors.black,
                                        //         fontSize: 15,
                                        //         fontWeight: FontWeight.bold
                                        //   ),),
                                        //     ],
                                        //  )
                                        
                                      
                                  ],
                              ),
                            )
                      
                     
                     ],
                ),
          ),
    );

  }


}