import 'dart:convert';

import 'package:flutter/material.dart';

import 'package:pdf/pdf.dart';
import 'package:shared_preferences/shared_preferences.dart';
import 'package:smartdalala/components/add.dart';
import 'package:smartdalala/components/model.dart';
import 'package:smartdalala/components/pdf.dart';

import 'package:flutter/material.dart';
import 'package:flutter/material.dart';
import 'package:http/http.dart' as http;


// late Autogenerated unpaid;

class DueList extends StatefulWidget {
  const DueList({ Key? key }) : super(key: key);

  @override
  _DueListState createState() => _DueListState();
}

class _DueListState extends State<DueList> {

  var menuList=[
       {
          'name':"Dalali Due",
           'Icon':Icons.pie_chart,
           'navigate':'/Dalailist'
       },
       {
          'name':"Date",
           'Icon':Icons.date_range,
           'navigate':'/DateList'
       },
       {
          'name':"RiceMill",
           'Icon':Icons.record_voice_over_sharp,
           'navigate':'/RiceMill'
       },
       {
          'name':"PartyName",
           'Icon':Icons.production_quantity_limits_sharp,
           'navigate':'/PartyName'
       },
       {
          'name':"Paid",
           'Icon':Icons.paid,
           'navigate':'/Paid'
       },
       
       {
          'name':"Unpaid",
           'Icon':Icons.accessible_forward,
           'navigate':'/unPaid'
       },   
       {
          'name':"Both",
           'Icon':Icons.person,
           'navigate':'/Both'
       },
       {
          'name':"Days",
           'Icon':Icons.dynamic_feed_sharp,
           'navigate':'/Add'
       },

  ];


   

 void getUnpaid()async{
         
          final SharedPreferences Detailsuser = await SharedPreferences.getInstance();
          final String id = Detailsuser.getString('id').toString();
          //  http://localhost:5000
          var url="${path}/admin/display/unpaid/"+userid;

          try{
          final response = await http.get(Uri.parse(url));
          if (response.statusCode == 200) {
              setState(() {
              //  unpaid = Autogenerated.fromJson(jsonDecode(response.body));
              });
             
          } else {
            // throw Exception('Failed to load album');
          }
          }catch(e){
              print(e);
          }
  }

  @override
  void initState() {
    getUnpaid();
    super.initState();
  }



  @override
  Widget build(BuildContext context) {
    return Scaffold(
      //  drawer: Drawer(),
      floatingActionButton: CircleAvatar(child: IconButton(onPressed: (){
           Navigator.pushNamed(context, "/Add");
      },icon: Icon(Icons.add),)),
      appBar: AppBar(
               backgroundColor: Colors.orange,
               title:const Center(child: Text("Due List",style: TextStyle(
                     color: Colors.black,
                     fontSize: 25,
                     fontWeight: FontWeight.bold
               ),)),
          ),
      body: Container(
          width: MediaQuery.of(context).size.width,
          // height: MediaQuery.of(context).size.height/1.1,
          
           child: Center(
             child: Wrap(
                alignment: WrapAlignment.center,
                crossAxisAlignment:WrapCrossAlignment.center,
                 children: [
                       divCard(menuList[0]['name'],menuList[0]['Icon'],menuList[0]['navigate']),
                       divCard(menuList[1]['name'],menuList[1]['Icon'],menuList[1]['navigate']),
                       divCard(menuList[2]['name'],menuList[2]['Icon'],menuList[2]['navigate']),
                       divCard(menuList[3]['name'],menuList[3]['Icon'],menuList[3]['navigate']),
                       divCard(menuList[4]['name'],menuList[4]['Icon'],menuList[4]['navigate']),
                       divCard(menuList[5]['name'],menuList[5]['Icon'],menuList[5]['navigate']),
                       divCard(menuList[6]['name'],menuList[6]['Icon'],menuList[6]['navigate']),
                       divCard(menuList[7]['name'],menuList[7]['Icon'],menuList[7]['navigate']),
           
                 ],
             ),
           ),
      ),
    );
  }


 Widget divCard(name,Icons,nav){

  return InkWell(
    onTap: (){
         Navigator.pushNamed(context, nav,);  
    },
    child: Container(
      width: 150,
      height: 150,
      child: Card(
          
           child:Column(
               mainAxisAlignment: MainAxisAlignment.center,
               crossAxisAlignment: CrossAxisAlignment.center,
               children: [  
                      Text(name,style:const TextStyle(
                                                  fontSize: 20,
                                                  color: Colors.black,
                                                  fontWeight: FontWeight.bold
                                              ),
                                              textAlign: TextAlign.center,
                       ),
                      const SizedBox(height: 20,),
                      Icon(Icons,size: 40,color: Colors.pink)
                    
               ],
           ), 
      ),
    ),
  );
 }


}