import 'dart:convert';

import 'package:flutter/material.dart';
import 'package:pdf/pdf.dart';
import 'package:shared_preferences/shared_preferences.dart';
import 'package:smartdalala/components/Duelist.dart';
import 'package:smartdalala/components/add.dart';
import 'package:smartdalala/components/menu.dart';
import 'package:smartdalala/components/model.dart';
import 'package:smartdalala/components/pdf.dart';
import 'package:smartdalala/components/table.dart';


import 'package:flutter/material.dart';
import 'package:flutter/material.dart';
import 'package:http/http.dart' as http;


class Unpaid extends StatefulWidget {
  const Unpaid({ Key? key }) : super(key: key);

  @override
  _UnpaidState createState() => _UnpaidState();
}

class _UnpaidState extends State<Unpaid> {
 
  late Autogenerated unpaid;


  void onchangeDate(){
     
      List<Items> list=[];

      list=originalData.items!.where((item) => !item.paid!).toList(); 
      searchData.items=list;
      f.value=!f.value;

}


 bool flag=true;
   void getUnpaid()async{
         
          final SharedPreferences Detailsuser = await SharedPreferences.getInstance();
          final String id = Detailsuser.getString('id').toString();
          //  http://localhost:5000
          var url="${path}/admin/display/"+userid;
           print("unpaid url path");
           print(url);
          try{
          final response = await http.get(Uri.parse(url));
          print(response.statusCode);
          if (response.statusCode == 200) {
              setState(() {
                  unpaid = Autogenerated.fromJson(jsonDecode(response.body));
                  onchangeDate();
                  flag=false;

              });
             
          } else {
            // throw Exception('Failed to load album');
            print("error");
          }
          }catch(e){
              print(e);
          }
  }

  @override
  void initState() {
    super.initState();
    onchangeDate();
  }
 
  @override
  Widget build(BuildContext context) {
     return Scaffold(
      appBar: AppBar(
               backgroundColor: Colors.orange,
                leading: getBack(context),
               title:const Center(child: Text("Un Paid",style: TextStyle(
                     color: Colors.black,
                     fontSize: 25,
                     fontWeight: FontWeight.bold
               ),)),
      ),
      floatingActionButton: InkWell(
        onTap: (){
              generatePdf(PdfPageFormat.a4,"Balaji Vasvi",unpaid,context);
        },
        child: Container(
           decoration: BoxDecoration(
           color: Colors.cyan,
           borderRadius: BorderRadius.circular(100)
           ),
           child: Icon(Icons.print,color: Colors.black,),
           padding: EdgeInsets.all(10),
        ),
      ),
      body:   TableDisplay(data: "",)
    ); 
  }
}